"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Customers",
      [
        {
          name: "Mohammad Zai",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 1658700,
          balance: 1658700,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Niyaz Ali",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 471000,
          balance: 471000,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Malik Amjad",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 1592600,
          balance: 1592600,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Zam Zam",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 389761,
          balance: 389761,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Babudin",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 80300,
          balance: 80300,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Sheri khan 1",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 729100,
          balance: 729100,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Sheri khan 2",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 389800,
          balance: 389800,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Zaheer",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 115550,
          balance: 115550,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Rizwan",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 215500,
          balance: 215500,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Kaleemullah",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 700000,
          balance: 700000,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Akber",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 19000,
          balance: 19000,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Sheikh Habibullah",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 1272700,
          balance: 1272700,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Haji Usman",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 135500,
          balance: 135500,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Zaheer Hasani",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 2064270,
          balance: 2064270,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Sardar Karachi",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 249000,
          balance: 249000,
          amountTypeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Karachi Shop",
          address: "Shop No 140",
          phoneNumber: 923138871521,
          startingBalance: 0,
          balance: 0,
          amountTypeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Laal Muhammad Saraf",
          address: "unknown",
          phoneNumber: 0,
          startingBalance: 0,
          balance: 0,
          amountTypeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Home Expense",
          address: "Home",
          phoneNumber: 0,
          startingBalance: 0,
          balance: 0,
          amountTypeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Zakat",
          address: "Zakat",
          phoneNumber: 0,
          startingBalance: 0,
          balance: 0,
          amountTypeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Customers", null, {});
  },
};
